### ISSUE TITLE
Final checklist to go thru before Review 2 (Please add everything you feel should be confirmed before sending project to second review)

### ISSUE THREAD

**Issue by Student2506** [Student2506/practicum-android-diploma#105]
1. Криты
2. Все элементы ресурсов UI оптимизированы (нет 2 одинаковых png на разных модулях, аналогично с адаптерами, item layout и т.д.) 
3. Не вливаем задачи следующих эпиков раньше времени?
4. Проверить стили (был разрешен конфликт при мердже экранов избранного и поиска)

**Comment by MonomythConvergence** [comment]
5. Вычистить findViewById
6. Перейти на Plurals в моей части (layout поиска) - сделано 
7. Добавить debounce

**Comment by MonomythConvergence** [comment]
8. Пройтись по layout и перевести всё в dimens?
