### ISSUE TITLE
Secondary issues

### ISSUE THREAD

**Issue by MonomythConvergence** [Student2506/practicum-android-diploma#171]
Список второстепенных мелочей или вопросов к которым хочется потом вернуться а сейчас нет времени, добавки в комментах приветствуются 

Отступы от кнопки назад - сейчас убраны, по идее должно быть 4dp

**Comment by MonomythConvergence** [comment]
Цвет текста "Ожидаемая зарплата" в фильтре когда у вьюхи нет фокуса должен быть черный, но сейчас при нажатии он навсегда становится синим.

**Comment by Student2506** [comment]
Кнопка "Выбрать" на экране "Выбор места работы" ещё появляется, но никуда не ведёт

**Comment by Student2506** [comment]
Выбора страны/региона требуется нажимать именно на иконку, а не на поле "Страна"/"Регион" чтобы перейти к выбору

**Comment by Student2506** [comment]
Логику возврата доработать 

Снимать со стека Место Работы и Отрасль совсем, иначе при возврате с экрана "Настройки фильтрации" он заходит в них тоже...

**Comment by Student2506** [comment]
Фильтр падает при нажатии несколько раз

**Comment by Student2506** [comment]
Если фильтр открыть на "Выбор месте работы" и страну оставить, а пойти сразу в регион... то никаких регионов не показывается...
