### ISSUE TITLE
Review 1 Issue 2 : fix lateinit to nullable for Activity and change fragment's bindin to nullable + backing field

### ISSUE THREAD

**Issue by Student2506** [Student2506/practicum-android-diploma#39]
В активити биндинг можно делать через `lateinit` - для активити это безопасно, а во фрагментах нужно делать нуллабельный и через backing field

_Originally posted by @ArturNurtdinov in https://github.com/Student2506/practicum-android-diploma/pull/33#discussion_r1779472896_

**Comment by MonomythConvergence** [comment]
[search/src/main/java/ru/practicum/android/diploma/search/presentation/ui/CountryFragment.kt](https://github.com/Student2506/practicum-android-diploma/pull/33/files/0b7581df302ab0125c150892fb29f200c3b75f9e#diff-1f226deacc9e9f6470d70e137d15626c738ad047bada88a73fb304ddc1d5ac5b)
import ru.practicum.android.diploma.search.databinding.FragmentCountryBinding

class CountryFragment : Fragment() {
    private var _binding: FragmentCountryBinding? = null
@[ArturNurtdinov](https://github.com/ArturNurtdinov) ArturNurtdinov [2 hours ago](https://github.com/Student2506/practicum-android-diploma/pull/33#discussion_r1779477090)
При использовании viewBinding во фрагментах обязательно нужно обнулять _binding в onDestroyView, иначе будет утечка памяти. Почитать о том, как использовать эту фичу во фрагментах можно тут - https://developer.android.com/topic/libraries/view-binding#fragments. Почитать подробнее про утечку можно здесь - https://stackoverflow.com/questions/65295104/android-view-binding-clear-binding-in-fragment-lifecycle
